version: '3'

services:
  congreso-frontend:
    build:
      context: ./Proyecto_Congreso_2025-main
      dockerfile: Dockerfile
    restart: always
    environment:
      - VIRTUAL_HOST=sistemasumgcoban.com.gt
      - LETSENCRYPT_HOST=sistemasumgcoban.com.gt
      - LETSENCRYPT_EMAIL=tu@correo.com
    networks:
      - web
    expose:
      - "80"

networks:
  web:
    external: true
